[options]
# repo = "/example/path"

# Note that by default sync_packages is false
sync_packages = true
# shadowmire_upstream = "http://example.com/pypi/web/"
# use_pypi_index = true

exclude = [
    "^[a-z]"
]
# Include patterns have higher priority than exclude patterns.
# Packages matching include patterns will be included even if they also match exclude patterns.
# include = ["^requests$"]
prerelease_exclude = [
    ".+"
]
excluded_wheel_filename = []
skip_yanked = false
# skip_old_packages_days = 1095
filter_metadata = true
least_releases_to_keep = 0
